const fs = require('fs');
let html = fs.readFileSync('index.html', 'utf8');

// Remove <div id="csat-board" style="display:none"></div>
html = html.replace('      <div id="csat-board" style="display:none"></div>\n', '');

// Also revert the study-tabs button I added earlier
const tabButton = '          <button class="view-btn" id="study-tab-csat" onclick="switchStudyTab(\'csat\')">기출 채점</button>\n';
html = html.replace(tabButton, '');

// Also revert the changes in renderStudyTabs and loadStudyBoard to keep things clean
// Actually, it's safer to just inject <div class="page" id="page-csat-board" style="display:none"></div>
// right before <div class="page" id="page-study-board">
const pageStart = '<div class="page" id="page-study-board">';
const newPage = `<div class="page" id="page-csat-board" style="display:none">
  <!-- Content will be generated by csat.js -->
  <div id="csat-board"></div>
</div>
`;
html = html.replace(pageStart, newPage + pageStart);

fs.writeFileSync('index.html', html);
console.log('Moved to own page');
